version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.7
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            gem install bundler
            bundle install
            bundle exec rake test